### Create a user
POST http://localhost:8000/user/1
Content-Type: application/json

{
  "balance": 5
}

### Get a user
GET http://localhost:8000/user/1

### Post a mint transaction
POST http://localhost:8000/mint/1
Content-Type: application/json

{
  "toAddress": "2",
  "mintAmount": 5
}
